// One entry per master, keyed by the URL slug used in nav.js paths
// (/masters/<slug>). Drives the generic MasterCrudPage: which API to hit,
// what the list shows, and what the create/edit form fields are.
export const mastersSchemas = {
  'cost-centre-types': {
    title: 'Cost Centre Types',
    menuKey: 'masters.cost_centre_types',
    apiBase: '/api/masters/cost-centre-types/',
    idField: 'cost_centre_type_id',
    nameField: 'cost_centre_type_name',
    activeField: 'cost_centre_type_active',
    listSecondary: (r) => r.cost_centre_type_shortname,
    fields: [
      { name: 'cost_centre_type_name', label: 'Name', required: true },
      { name: 'cost_centre_type_shortname', label: 'Short name', required: true },
      { name: 'cost_centre_type_active', label: 'Active', type: 'active-select' },
    ],
  },
  contractors: {
    title: 'Contractors',
    menuKey: 'masters.contractors',
    apiBase: '/api/masters/contractors/',
    idField: 'contractor_id',
    nameField: 'contractor_name',
    activeField: null,
    fields: [{ name: 'contractor_name', label: 'Name', required: true }],
  },
  'cert-institutes': {
    title: 'Cert Institutes',
    menuKey: 'masters.cert_institutes',
    apiBase: '/api/masters/cert-institutes/',
    idField: 'cert_institute_id',
    nameField: 'cert_institute_name',
    activeField: null,
    listSecondary: (r) => r.cert_institute_shortname,
    fields: [
      { name: 'cert_institute_name', label: 'Name', required: true },
      { name: 'cert_institute_shortname', label: 'Short name', required: true },
      { name: 'cert_institute_address', label: 'Address', wide: true },
      { name: 'location_id', label: 'Location ID', type: 'number', required: true },
      { name: 'tel_no', label: 'Telephone' },
    ],
  },
  'email-notification-types': {
    title: 'Email Notification Types',
    menuKey: 'masters.email_notification_types',
    apiBase: '/api/masters/email-notification-types/',
    idField: 'en_type_id',
    nameField: 'en_type_name',
    activeField: 'en_type_active',
    fields: [
      { name: 'en_type_name', label: 'Name', required: true },
      { name: 'en_type_subject', label: 'Email subject', required: true, wide: true },
      { name: 'en_description', label: 'Description', type: 'textarea', required: true },
      { name: 'en_type_active', label: 'Active', type: 'active-select' },
    ],
  },
  operators: {
    title: 'Operators',
    menuKey: 'masters.operators',
    apiBase: '/api/masters/operators/',
    idField: 'operator_id',
    nameField: 'operator_name',
    activeField: 'operator_active',
    listSecondary: (r) => r.operator_short_name,
    fields: [
      { name: 'operator_name', label: 'Name', required: true },
      { name: 'operator_short_name', label: 'Short name', required: true },
      { name: 'operator_sap_code', label: 'SAP code' },
      { name: 'wbs_client_code', label: 'WBS client code' },
      { name: 'location_id', label: 'Location ID', type: 'number' },
      { name: 'country_id', label: 'Country ID', type: 'number' },
      { name: 'contact_person', label: 'Contact person' },
      { name: 'tel_no', label: 'Telephone' },
      { name: 'email_id', label: 'Email', type: 'email' },
      { name: 'operator_active', label: 'Active', type: 'active-select' },
    ],
  },
  rigs: {
    title: 'Rigs',
    menuKey: 'masters.rigs',
    apiBase: '/api/masters/rigs/',
    idField: 'rig_id',
    nameField: 'rig_name',
    activeField: 'rig_active',
    listSecondary: (r) => r.rig_short_name,
    fields: [
      { name: 'rig_name', label: 'Name', required: true },
      { name: 'rig_short_name', label: 'Short name', required: true },
      { name: 'old_rig_name', label: 'Old name' },
      { name: 'rig_subtype_id', label: 'Rig Subtype ID', type: 'number', required: true },
      { name: 'rig_type_id', label: 'Rig Type ID', type: 'number', required: true },
      { name: 'rig_built_dt', label: 'Built date', type: 'date', required: true },
      { name: 'rig_tel_no', label: 'Telephone' },
      { name: 'rig_fax_no', label: 'Fax' },
      { name: 'rig_email_id', label: 'Email', type: 'email' },
      { name: 'personnel_area', label: 'Personnel area' },
      { name: 'org_unit_code', label: 'Org unit code' },
      { name: 'rig_from', label: 'From', type: 'date', required: true },
      { name: 'rig_active', label: 'Active', type: 'active-select' },
    ],
  },
  'cost-centres': {
    title: 'Cost Centres',
    menuKey: 'masters.cost_centres',
    apiBase: '/api/masters/cost-centres/',
    idField: 'cost_centre_id',
    nameField: 'cost_centre_name',
    activeField: 'cost_centre_active',
    listSecondary: (r) => r.cost_centre_type_name || '',
    fields: [
      { name: 'cost_centre_name', label: 'Name', required: true },
      { name: 'old_cost_centre_name', label: 'Old name' },
      {
        name: 'cost_centre_type',
        label: 'Cost Centre Type',
        type: 'select-remote',
        remote: '/api/masters/cost-centre-types/',
        optionLabel: 'cost_centre_type_name',
        optionValue: 'cost_centre_type_id',
        labelField: 'cost_centre_type_name',
      },
      {
        name: 'rig',
        label: 'Rig',
        type: 'select-remote',
        remote: '/api/masters/rigs/',
        optionLabel: 'rig_name',
        optionValue: 'rig_id',
        labelField: 'rig_name',
      },
      { name: 'fs_emp_id', label: 'Employee ID', type: 'number' },
      { name: 'location_id', label: 'Location ID', type: 'number' },
      { name: 'cost_centre_active', label: 'Active', type: 'active-select' },
    ],
  },
  competency: {
    title: 'Competency',
    menuKey: 'masters.competency',
    apiBase: '/api/masters/competency/',
    idField: 'competency_id',
    nameField: 'competency_name',
    activeField: 'active',
    listSecondary: (r) => r.department_name || '',
    fields: [
      { name: 'competency_name', label: 'Name', required: true },
      {
        name: 'department',
        label: 'Department',
        type: 'select-remote',
        // Competency's Dept_Id is really a fixed 3-way category (HSE /
        // Technical Services / HR), not a pick from the full org chart —
        // that's what the legacy data actually uses it for.
        remote: '/api/masters/departments/?ids=3,14,35',
        optionLabel: 'dept_dispname',
        optionValue: 'dept_id',
        labelField: 'department_name',
        required: true,
      },
      { name: 'active', label: 'Active', type: 'active-select' },
    ],
  },
  'fs-categories': {
    title: 'Fs Categories',
    menuKey: 'masters.fs_categories',
    apiBase: '/api/masters/fs-categories/',
    idField: 'fs_category_id',
    nameField: 'fs_category_name',
    activeField: null,
    fields: [{ name: 'fs_category_name', label: 'Name', required: true }],
  },
  ranks: {
    title: 'Ranks',
    menuKey: 'masters.ranks',
    apiBase: '/api/masters/ranks/',
    idField: 'rank_id',
    nameField: 'rank_name',
    activeField: null,
    listSecondary: (r) => r.fs_category_name || '',
    fields: [
      { name: 'rank_name', label: 'Name', required: true },
      { name: 'rank_abrv', label: 'Abbreviation', required: true },
      {
        name: 'fs_category',
        label: 'Category',
        type: 'select-remote',
        remote: '/api/masters/fs-categories/',
        optionLabel: 'fs_category_name',
        optionValue: 'fs_category_id',
        labelField: 'fs_category_name',
        required: true,
      },
      { name: 'vessel_dept_id', label: 'Vessel Dept ID', type: 'number', required: true },
      { name: 'rank_order', label: 'Order', type: 'number' },
    ],
  },
  'travel-eligibility': {
    title: 'Travel Eligibility',
    menuKey: 'masters.travel_eligibility',
    apiBase: '/api/masters/travel-eligibility/',
    idField: 'travel_eligibility_id',
    nameField: 'display_name',
    activeField: null,
    dateActiveField: 'eligible_to',
    listSecondary: (r) => r.travel_class,
    fields: [
      {
        name: 'rank',
        label: 'Rank',
        type: 'select-remote',
        remote: '/api/masters/ranks/',
        optionLabel: 'rank_name',
        optionValue: 'rank_id',
        labelField: 'rank_name',
        required: true,
      },
      {
        name: 'travel_mode',
        label: 'Travel Mode',
        type: 'select',
        options: [
          { value: 'A', label: 'Air' },
          { value: 'R', label: 'Rail' },
          { value: 'C', label: 'Coach' },
        ],
        required: true,
      },
      { name: 'travel_class', label: 'Travel Class', required: true, wide: true },
      { name: 'travel_preference', label: 'Preference (1 = first choice)', type: 'number' },
      { name: 'eligible_from', label: 'Eligible From', type: 'date', required: true },
      {
        name: 'eligible_to',
        label: 'Eligible To',
        type: 'date',
        hint: 'Leave blank while still eligible',
      },
    ],
  },
  'reporting-structure': {
    title: 'Reporting Structure',
    menuKey: 'masters.reporting_structure',
    apiBase: '/api/masters/reporting-structure/',
    idField: 'reporting_structure_id',
    nameField: 'display_name',
    activeField: null,
    listSecondary: (r) => (r.reporting_rank_name ? `Reports to ${r.reporting_rank_name}` : 'Top of chain'),
    fields: [
      {
        name: 'fs_category',
        label: 'Category',
        type: 'select-remote',
        remote: '/api/masters/fs-categories/',
        optionLabel: 'fs_category_name',
        optionValue: 'fs_category_id',
        labelField: 'fs_category_name',
        required: true,
      },
      {
        name: 'rank',
        label: 'Rank',
        type: 'select-remote',
        remote: '/api/masters/ranks/',
        optionLabel: 'rank_name',
        optionValue: 'rank_id',
        labelField: 'rank_name',
        filterField: 'fs_category',
        filterOptionField: 'fs_category',
        filterPlaceholder: 'Select a category first…',
        required: true,
      },
      {
        name: 'reporting_rank',
        label: 'Reports To',
        type: 'select-remote',
        remote: '/api/masters/ranks/',
        optionLabel: 'rank_name',
        optionValue: 'rank_id',
        labelField: 'reporting_rank_name',
        filterField: 'fs_category',
        filterOptionField: 'fs_category',
        filterPlaceholder: 'Select a category first…',
      },
    ],
  },
  'rig-operations': {
    title: 'Rig Operations',
    menuKey: 'masters.rig_operations',
    apiBase: '/api/masters/rig-operations/',
    idField: 'rig_operation_id',
    nameField: 'rig_operation_name',
    activeField: null,
    fields: [{ name: 'rig_operation_name', label: 'Name', required: true, wide: true }],
  },
  'contact-exposure-types': {
    title: 'Contact Exposure Types',
    menuKey: 'masters.contact_exposure_types',
    apiBase: '/api/masters/contact-exposure-types/',
    idField: 'contact_expo_type_id',
    nameField: 'contact_expo_type_name',
    activeField: null,
    fields: [{ name: 'contact_expo_type_name', label: 'Name', required: true }],
  },
  'indicator-types': {
    title: 'Indicator Types',
    menuKey: 'masters.indicator_types',
    apiBase: '/api/masters/indicator-types/',
    idField: 'indicator_type_id',
    nameField: 'indicator_type_name',
    activeField: null,
    listSecondary: (r) => r.report_type,
    fields: [
      { name: 'indicator_type_name', label: 'Name', required: true },
      {
        name: 'report_type',
        label: 'Report Type',
        type: 'select',
        options: [
          { value: 'Leading', label: 'Leading' },
          { value: 'Lagging', label: 'Lagging' },
        ],
        required: true,
      },
    ],
  },
  'indicator-subtypes': {
    title: 'Indicator Subtypes',
    menuKey: 'masters.indicator_subtypes',
    apiBase: '/api/masters/indicator-subtypes/',
    idField: 'indicator_subtype_id',
    nameField: 'indicator_subtype_name',
    activeField: null,
    listSecondary: (r) => r.indicator_type_name || '',
    fields: [
      {
        name: 'indicator_type',
        label: 'Indicator Type',
        type: 'select-remote',
        remote: '/api/masters/indicator-types/',
        optionLabel: 'indicator_type_name',
        optionValue: 'indicator_type_id',
        labelField: 'indicator_type_name',
        required: true,
      },
      { name: 'indicator_subtype_name', label: 'Name', required: true, wide: true },
    ],
  },
  'parts-of-body': {
    title: 'Parts Of Body',
    menuKey: 'masters.parts_of_body',
    apiBase: '/api/masters/parts-of-body/',
    idField: 'part_of_body_id',
    nameField: 'part_of_body_name',
    activeField: null,
    formNote:
      'If a Parts Of Body description is modified, the change must also be made in the Excel Format and other related modules.',
    fields: [{ name: 'part_of_body_name', label: 'Name', required: true, wide: true }],
  },
  'qhse-categories': {
    title: 'QHSE Categories',
    menuKey: 'masters.qhse_categories',
    apiBase: '/api/masters/qhse-categories/',
    idField: 'qhse_category_id',
    nameField: 'qhse_category_name',
    activeField: null,
    fields: [{ name: 'qhse_category_name', label: 'Name', required: true, wide: true }],
  },
  'hse-activities': {
    title: 'HSE Activities',
    menuKey: 'masters.hse_activities',
    apiBase: '/api/masters/hse-activities/',
    idField: 'hse_activity_id',
    nameField: 'hse_activity_name',
    activeField: null,
    listSecondary: (r) => r.hse_activity_type_display || '',
    fields: [
      { name: 'hse_activity_name', label: 'Name', required: true },
      {
        name: 'hse_activity_type',
        label: 'Type',
        type: 'select',
        options: [
          { value: 'IN', label: 'Inspection' },
          { value: 'DR', label: 'Drill' },
          { value: 'AU', label: 'Audit' },
          { value: 'OT', label: 'Other' },
        ],
        required: true,
      },
    ],
  },
  'hse-consumables': {
    title: 'HSE Consumables',
    menuKey: 'masters.hse_consumables',
    apiBase: '/api/masters/hse-consumables/',
    idField: 'hse_consumable_id',
    nameField: 'hse_consumable_name',
    activeField: null,
    listSecondary: (r) => r.hse_consumption_unit,
    fields: [
      { name: 'hse_consumable_name', label: 'Name', required: true, wide: true },
      { name: 'hse_consumption_unit', label: 'Consumption Unit', required: true },
    ],
  },
  'hazard-types': {
    title: 'Hazard Types',
    menuKey: 'masters.hazard_types',
    apiBase: '/api/masters/hazard-types/',
    idField: 'haz_type_id',
    nameField: 'haz_type_name',
    activeField: 'haz_type_active',
    listSecondary: (r) => r.haz_type_class,
    fields: [
      { name: 'haz_type_name', label: 'Name', required: true },
      {
        name: 'haz_type_class',
        label: 'Class',
        type: 'select',
        options: [
          { value: 'Positive', label: 'Positive' },
          { value: 'Negative', label: 'Negative' },
        ],
        required: true,
      },
      { name: 'haz_type_active', label: 'Active', type: 'active-select' },
    ],
  },
  'user-rig-mapping': {
    title: 'User Rig Mapping',
    menuKey: 'masters.user_rig_mapping',
    apiBase: '/api/masters/user-rig-mapping/',
    idField: 'user_rig_mapping_id',
    nameField: 'display_name',
    activeField: null,
    dateActiveField: 'mapping_to',
    listSecondary: (r) => r.user_login_id,
    fields: [
      {
        name: 'user',
        label: 'User',
        type: 'search-remote',
        remote: '/api/masters/users/',
        optionLabel: 'display_name',
        optionValue: 'user_id',
        labelField: 'user_name',
        required: true,
      },
      {
        name: 'rig',
        label: 'Rig',
        type: 'select-remote',
        remote: '/api/masters/rigs/',
        optionLabel: 'rig_name',
        optionValue: 'rig_id',
        labelField: 'rig_name',
        required: true,
      },
      { name: 'mapping_from', label: 'From', type: 'date', required: true },
      { name: 'mapping_to', label: 'To', type: 'date', hint: 'Leave blank while active' },
    ],
  },
  'user-category-mapping': {
    title: 'User Category Mapping',
    menuKey: 'masters.user_category_mapping',
    apiBase: '/api/masters/user-category-mapping/',
    idField: 'user_fs_catg_mapping_id',
    nameField: 'display_name',
    activeField: null,
    dateActiveField: 'mapping_to',
    listSecondary: (r) => r.user_login_id,
    fields: [
      {
        name: 'user',
        label: 'User',
        type: 'search-remote',
        remote: '/api/masters/users/',
        optionLabel: 'display_name',
        optionValue: 'user_id',
        labelField: 'user_name',
        required: true,
      },
      {
        name: 'fs_category',
        label: 'Category',
        type: 'select-remote',
        remote: '/api/masters/fs-categories/',
        optionLabel: 'fs_category_name',
        optionValue: 'fs_category_id',
        labelField: 'fs_category_name',
        required: true,
      },
      { name: 'mapping_from', label: 'From', type: 'date', required: true },
      { name: 'mapping_to', label: 'To', type: 'date', hint: 'Leave blank while active' },
    ],
  },
  'doc-to-sign-mapping': {
    title: 'Document To Sign Mapping',
    menuKey: 'masters.doc_to_sign_mapping',
    apiBase: '/api/masters/doc-to-sign-mapping/',
    idField: 'doc_to_sign_id',
    nameField: 'display_name',
    activeField: null,
    dateActiveField: 'sign_to',
    listSecondary: (r) => r.employee_name || '',
    fields: [
      { name: 'doc_name', label: 'Document Name', required: true, wide: true },
      {
        name: 'employee',
        label: 'Employee',
        type: 'search-remote',
        remote: '/api/masters/employees/',
        optionLabel: 'display_name',
        optionValue: 'emp_id',
        labelField: 'employee_name',
        required: true,
      },
      // Legacy stores this as a plain typed-in path, not an upload —
      // matches the original /Images/Signatures/<empId>.jpg convention.
      { name: 'sign_path', label: 'Sign Path', wide: true },
      { name: 'sign_from', label: 'From', type: 'date', required: true },
      { name: 'sign_to', label: 'To', type: 'date', hint: 'Leave blank while active' },
    ],
  },
  'interviewer-mapping': {
    title: 'Department To Interviewer Mapping',
    menuKey: 'masters.interviewer_mapping',
    apiBase: '/api/masters/interviewer-mapping/',
    idField: 'interviewer_id',
    nameField: 'display_name',
    activeField: 'active',
    listSecondary: (r) => r.user_login_id || '',
    fields: [
      {
        name: 'department',
        label: 'Department',
        type: 'select-remote',
        // Only these 3 departments run interview panels — every other
        // department in the org has no interviewer role to map. Filtered
        // server-side (same pattern as Competency) rather than fetching
        // every department and discarding most of them client-side.
        remote: '/api/masters/departments/?ids=3,14,35',
        optionLabel: 'dept_dispname',
        optionValue: 'dept_id',
        labelField: 'department_name',
        required: true,
      },
      {
        name: 'user',
        label: 'User',
        type: 'search-remote',
        remote: '/api/masters/users/',
        optionLabel: 'display_name',
        optionValue: 'user_id',
        labelField: 'user_name',
        required: true,
      },
      {
        name: 'sign_path',
        label: 'Signature',
        type: 'file',
        uploadUrl: '/api/masters/interviewer-mapping/upload-sign/',
        uploadKeyField: 'user',
        uploadKeyParam: 'user_id',
        uploadKeyLabel: 'user',
        urlField: 'sign_url',
        accept: '.jpg,.jpeg,.png,.pdf',
      },
      { name: 'active', label: 'Active', type: 'active-select' },
    ],
  },
  'drilling-operations': {
    title: 'Drilling Operations',
    menuKey: 'masters.drilling_operations',
    apiBase: '/api/masters/drilling-operations/',
    idField: 'drilling_ops_id',
    nameField: 'drilling_ops_name',
    activeField: null,
    listSecondary: (r) => `Code ${r.drilling_ops_code_no}`,
    fields: [
      {
        name: 'drilling_ops_code_no',
        label: 'Code No',
        type: 'number',
        required: true,
        checkUnique: { url: '/api/masters/drilling-operations/check-code/', param: 'code' },
      },
      { name: 'drilling_ops_name', label: 'Operations Name', required: true },
    ],
  },
  'drilling-sections': {
    title: 'Drilling Sections',
    menuKey: 'masters.drilling_sections',
    apiBase: '/api/masters/drilling-sections/',
    idField: 'drilling_section_id',
    nameField: 'drilling_section_name',
    activeField: null,
    fields: [{ name: 'drilling_section_name', label: 'Section', required: true }],
  },
}
