import {
  IconDashboard,
  IconShield,
  IconUsers,
  IconHistory,
  IconLayers,
  IconHome,
  IconPlusCircle,
  IconBriefcase,
  IconAward,
  IconMail,
  IconStar,
  IconChevronsUp,
  IconTag,
  IconClipboard,
  IconPlane,
  IconGitBranch,
  IconWrench,
  IconExposure,
  IconActivity,
  IconTrendingUp,
  IconPerson,
  IconShieldCheck,
  IconFlask,
  IconAlertTriangle,
  IconLink,
  IconFileSignature,
  IconUserCheck,
} from '@/components/icons'
import {
  Laptop,
  MapPin,
  Tag,
  Tags,
  Factory,
  Package,
  Truck,
  Building2,
  Network,
  Building,
  Users,
  Cable,
  CalendarRange,
  Stamp,
  Ship,
  GraduationCap,
  IdCard,
  Wallet,
  ClipboardList,
  Layers3,
  Globe,
  Flag,
  Map,
  Users2,
  LogOut,
  Landmark,
  MailWarning,
  Drill,
  Gauge,
  HardDrive,
  Grid3x3,
} from 'lucide-react'

// Two-tier nav: leaf items render directly in the primary sidebar; a parent
// with `sections` gets one primary-sidebar entry, and its sections render in
// the secondary sidebar (each optionally its own collapsible header, e.g.
// Masters' "General" group) whenever the current route is under it.
//
// `menuKey` on a leaf item is the sys_menu / User Rights permission key —
// items without one (Dashboard, Admin's own pages) aren't permission-gated;
// items with one only show for users who can view that key (see
// lib/permissions.js `can()`).
export const navTree = [
  { key: 'home', label: 'Home', path: '/', icon: IconDashboard },
  {
    key: 'dashboards',
    label: 'Dashboards',
    icon: Gauge,
    sections: [
      {
        items: [
          {
            key: 'rig_utilisation',
            label: 'Rig Utilisation',
            path: '/dashboards/rig-utilisation',
            icon: IconTrendingUp,
            menuKey: 'dashboards.rig_utilisation',
          },
          {
            key: 'drilling_performance',
            label: 'Drilling Performance',
            path: '/dashboards/drilling-performance',
            icon: Drill,
            menuKey: 'dashboards.drilling_performance',
          },
          {
            key: 'fleet_operating_picture',
            label: 'Fleet Operating Picture',
            path: '/dashboards/fleet-operating-picture',
            icon: Map,
            menuKey: 'dashboards.fleet_operating_picture',
          },
          {
            key: 'contract_exposure',
            label: 'Contract Exposure',
            path: '/dashboards/contract-exposure',
            icon: Landmark,
            menuKey: 'dashboards.contract_exposure',
          },
          {
            key: 'npt_analysis',
            label: 'NPT Analysis',
            path: '/dashboards/npt-analysis',
            icon: IconAlertTriangle,
            menuKey: 'dashboards.npt_analysis',
          },
          {
            key: 'it_asset_overview',
            label: 'IT Asset Overview',
            path: '/dashboards/it-asset-overview',
            icon: HardDrive,
            menuKey: 'dashboards.it_asset_overview',
          },
          {
            key: 'incident_dashboard',
            label: 'Incident Dashboard',
            path: '/dashboards/incident-dashboard',
            icon: Grid3x3,
            menuKey: 'dashboards.incident_dashboard',
          },
          // Rig Health Index pulled from the nav for now (not removed —
          // see RigHealthDashboardPage.jsx / rig_health_dashboard.py,
          // still routed in App.jsx, just not linked from anywhere).
        ],
      },
    ],
  },
  {
    key: 'masters',
    label: 'Masters',
    path: '/masters',
    icon: IconLayers,
    sections: [
      {
        label: 'General',
        items: [
          {
            key: 'rigs',
            label: 'Rigs',
            path: '/masters/rigs',
            icon: IconHome,
            menuKey: 'masters.rigs',
          },
          {
            key: 'rig_types',
            label: 'Rig Type',
            path: '/masters/rig-types',
            icon: IconWrench,
            menuKey: 'masters.rig_types',
          },
          {
            key: 'rig_subtypes',
            label: 'Rig Subtype',
            path: '/masters/rig-subtypes',
            icon: Network,
            menuKey: 'masters.rig_subtypes',
          },
          {
            key: 'vessel_depts',
            label: 'Vessel Department',
            path: '/masters/vessel-depts',
            icon: Ship,
            menuKey: 'masters.vessel_depts',
          },
          {
            key: 'relations',
            label: 'Relation',
            path: '/masters/relations',
            icon: Users2,
            menuKey: 'masters.relations',
          },
          {
            key: 'business_systems',
            label: 'Business System',
            path: '/masters/business-systems',
            icon: Landmark,
            menuKey: 'masters.business_systems',
          },
          {
            key: 'cost_centres',
            label: 'Cost Centres',
            path: '/masters/cost-centres',
            icon: IconPlusCircle,
            menuKey: 'masters.cost_centres',
          },
          {
            key: 'cost_centre_types',
            label: 'Cost Centre Types',
            path: '/masters/cost-centre-types',
            icon: IconHome,
            menuKey: 'masters.cost_centre_types',
          },
          {
            key: 'operators',
            label: 'Operators',
            path: '/masters/operators',
            icon: IconUsers,
            menuKey: 'masters.operators',
          },
          {
            key: 'contractors',
            label: 'Contractors',
            path: '/masters/contractors',
            icon: IconBriefcase,
            menuKey: 'masters.contractors',
          },
          {
            key: 'cert_institutes',
            label: 'Cert Institutes',
            path: '/masters/cert-institutes',
            icon: IconAward,
            menuKey: 'masters.cert_institutes',
          },
          {
            key: 'email_notification_types',
            label: 'Email Notification Types',
            path: '/masters/email-notification-types',
            icon: IconMail,
            menuKey: 'masters.email_notification_types',
          },
          {
            key: 'company_locations',
            label: 'Company Location',
            path: '/masters/company-locations',
            icon: MapPin,
            menuKey: 'masters.company_locations',
          },
          {
            key: 'organisational_grps',
            label: 'Organisational Group',
            path: '/masters/organisational-grps',
            icon: Building2,
            menuKey: 'masters.organisational_grps',
          },
          {
            key: 'business_grps',
            label: 'Business Group',
            path: '/masters/business-grps',
            icon: Network,
            menuKey: 'masters.business_grps',
          },
          {
            key: 'companies',
            label: 'Company',
            path: '/masters/companies',
            icon: Building,
            menuKey: 'masters.companies',
          },
          {
            key: 'financial_years',
            label: 'Financial Year',
            path: '/masters/financial-years',
            icon: CalendarRange,
            menuKey: 'masters.financial_years',
          },
          {
            key: 'buss_cert_issue_authorities',
            label: 'Issuing Authority',
            path: '/masters/buss-cert-issue-authorities',
            icon: Stamp,
            menuKey: 'masters.buss_cert_issue_authorities',
          },
          {
            key: 'buss_cert_types',
            label: 'Certificate Type',
            path: '/masters/buss-cert-types',
            icon: IconAward,
            menuKey: 'masters.buss_cert_types',
          },
          {
            key: 'buss_certs',
            label: 'Certificates',
            path: '/masters/buss-certs',
            icon: IconClipboard,
            menuKey: 'masters.buss_certs',
          },
        ],
      },
      {
        label: 'HR',
        items: [
          {
            key: 'competency',
            label: 'Competency',
            path: '/masters/competency',
            icon: IconStar,
            menuKey: 'masters.competency',
          },
          {
            key: 'ranks',
            label: 'Ranks',
            path: '/masters/ranks',
            icon: IconChevronsUp,
            menuKey: 'masters.ranks',
          },
          {
            key: 'job_descriptions',
            label: 'Job Descriptions',
            path: '/masters/job-descriptions',
            icon: IconClipboard,
            menuKey: 'masters.job_descriptions',
          },
          {
            key: 'travel_eligibility',
            label: 'Travel Eligibility',
            path: '/masters/travel-eligibility',
            icon: IconPlane,
            menuKey: 'masters.travel_eligibility',
          },
          {
            key: 'reporting_structure',
            label: 'Reporting Structure',
            path: '/masters/reporting-structure',
            icon: IconGitBranch,
            menuKey: 'masters.reporting_structure',
          },
          {
            key: 'departments',
            label: 'Department',
            path: '/masters/departments',
            icon: Users,
            menuKey: 'masters.departments',
          },
        ],
      },
      {
        label: 'Certificate Classification',
        items: [
          {
            key: 'cert_types',
            label: 'Certificate Type',
            path: '/masters/cert-types',
            icon: IconAward,
            menuKey: 'masters.cert_types',
          },
          {
            key: 'certs',
            label: 'Certificates',
            path: '/masters/certs',
            icon: IconClipboard,
            menuKey: 'masters.certs',
          },
          {
            key: 'qualifications',
            label: 'Qualification',
            path: '/masters/qualifications',
            icon: GraduationCap,
            menuKey: 'masters.qualifications',
          },
        ],
      },
      {
        label: 'Employment Classification',
        items: [
          {
            key: 'emp_natures',
            label: 'Employment Nature',
            path: '/masters/emp-natures',
            icon: IdCard,
            menuKey: 'masters.emp_natures',
          },
          {
            key: 'emp_types',
            label: 'Employment Type',
            path: '/masters/emp-types',
            icon: Wallet,
            menuKey: 'masters.emp_types',
          },
        ],
      },
      {
        label: 'Service Particulars',
        items: [
          {
            key: 'serv_types',
            label: 'Service Type',
            path: '/masters/serv-types',
            icon: ClipboardList,
            menuKey: 'masters.serv_types',
          },
          {
            key: 'serv_subtypes',
            label: 'Service Subtype',
            path: '/masters/serv-subtypes',
            icon: Layers3,
            menuKey: 'masters.serv_subtypes',
          },
          {
            key: 'fs_catg_to_sstype',
            label: 'FS Category To Service Subtype',
            path: '/masters/fs-catg-to-sstype',
            icon: IconLink,
            menuKey: 'masters.fs_catg_to_sstype',
          },
        ],
      },
      {
        label: 'Incident Classification',
        items: [
          {
            key: 'incident_types',
            label: 'Incident Type',
            path: '/masters/incident-types',
            icon: IconAlertTriangle,
            menuKey: 'masters.incident_types',
          },
          {
            key: 'incident_causes',
            label: 'Incident Cause',
            path: '/masters/incident-causes',
            icon: IconActivity,
            menuKey: 'masters.incident_causes',
          },
          {
            key: 'incident_subcauses',
            label: 'Incident Subcause',
            path: '/masters/incident-subcauses',
            icon: IconActivity,
            menuKey: 'masters.incident_subcauses',
          },
          {
            key: 'work_locations',
            label: 'Work Location',
            path: '/masters/work-locations',
            icon: MapPin,
            menuKey: 'masters.work_locations',
          },
        ],
      },
      {
        label: 'Regional Information',
        items: [
          {
            key: 'continents',
            label: 'Continent',
            path: '/masters/continents',
            icon: Globe,
            menuKey: 'masters.continents',
          },
          {
            key: 'countries',
            label: 'Country',
            path: '/masters/countries',
            icon: Flag,
            menuKey: 'masters.countries',
          },
          {
            key: 'country_states',
            label: 'Country State',
            path: '/masters/country-states',
            icon: Map,
            menuKey: 'masters.country_states',
          },
          {
            key: 'locations',
            label: 'Location',
            path: '/masters/locations',
            icon: MapPin,
            menuKey: 'masters.locations',
          },
        ],
      },
      {
        label: 'Leave Masters',
        items: [
          {
            key: 'leaving_reasons',
            label: 'Leaving Reasons',
            path: '/masters/leaving-reasons',
            icon: LogOut,
            menuKey: 'masters.leaving_reasons',
          },
          {
            key: 'leaving_reason_details',
            label: 'Leaving Reason Details',
            path: '/masters/leaving-reason-details',
            icon: LogOut,
            menuKey: 'masters.leaving_reason_details',
          },
        ],
      },
      {
        label: 'Mail Alert Masters',
        items: [
          {
            key: 'mail_alerts',
            label: 'Alert Details',
            path: '/masters/mail-alerts',
            icon: MailWarning,
            menuKey: 'masters.mail_alerts',
          },
          {
            key: 'mail_alert_to_users',
            label: 'Alert To Users',
            path: '/masters/mail-alert-to-users',
            icon: IconLink,
            menuKey: 'masters.mail_alert_to_users',
          },
          {
            key: 'mail_recipient_mappings',
            label: 'Mail Recipient Mapping',
            path: '/masters/mail-recipient-mappings',
            icon: IconLink,
            menuKey: 'masters.mail_recipient_mappings',
          },
          {
            key: 'notification_triggers',
            label: 'Notification Triggers',
            path: '/masters/notification-triggers',
            icon: IconLink,
            menuKey: 'masters.notification_triggers',
          },
        ],
      },
      {
        label: 'QHSE',
        items: [
          {
            key: 'rig_operations',
            label: 'Rig Operation',
            path: '/masters/rig-operations',
            icon: IconWrench,
            menuKey: 'masters.rig_operations',
          },
          {
            key: 'contact_exposure_types',
            label: 'Contact Exposure Type',
            path: '/masters/contact-exposure-types',
            icon: IconExposure,
            menuKey: 'masters.contact_exposure_types',
          },
          {
            key: 'indicator_types',
            label: 'Indicator Type',
            path: '/masters/indicator-types',
            icon: IconActivity,
            menuKey: 'masters.indicator_types',
          },
          {
            key: 'indicator_subtypes',
            label: 'Indicator Subtype',
            path: '/masters/indicator-subtypes',
            icon: IconTrendingUp,
            menuKey: 'masters.indicator_subtypes',
          },
          {
            key: 'parts_of_body',
            label: 'Parts Of Body',
            path: '/masters/parts-of-body',
            icon: IconPerson,
            menuKey: 'masters.parts_of_body',
          },
          {
            key: 'qhse_categories',
            label: 'QHSE Category',
            path: '/masters/qhse-categories',
            icon: IconShieldCheck,
            menuKey: 'masters.qhse_categories',
          },
          {
            key: 'hse_activities',
            label: 'HSE Activity',
            path: '/masters/hse-activities',
            icon: IconActivity,
            menuKey: 'masters.hse_activities',
          },
          {
            key: 'hse_consumables',
            label: 'HSE Consumable',
            path: '/masters/hse-consumables',
            icon: IconFlask,
            menuKey: 'masters.hse_consumables',
          },
          {
            key: 'hse_manhours_parties',
            label: 'HSE Manhours Party',
            path: '/masters/hse-manhours-parties',
            icon: IconUsers,
            menuKey: 'masters.hse_manhours_parties',
          },
          {
            key: 'hse_meetings',
            label: 'HSE Meeting',
            path: '/masters/hse-meetings',
            icon: IconClipboard,
            menuKey: 'masters.hse_meetings',
          },
          {
            key: 'hse_drills',
            label: 'HSE Drill',
            path: '/masters/hse-drills',
            icon: IconAlertTriangle,
            menuKey: 'masters.hse_drills',
          },
          {
            key: 'hazard_types',
            label: 'Hazard Type',
            path: '/masters/hazard-types',
            icon: IconAlertTriangle,
            menuKey: 'masters.hazard_types',
          },
          {
            key: 'qhse_activities',
            label: 'Activity',
            path: '/masters/activities',
            icon: IconActivity,
            menuKey: 'qhse.activities',
          },
        ],
      },
      {
        label: 'User Mapping Masters',
        items: [
          {
            key: 'user_rig_mapping',
            label: 'User Rig Mapping',
            path: '/masters/user-rig-mapping',
            icon: IconLink,
            menuKey: 'masters.user_rig_mapping',
          },
          {
            key: 'user_category_mapping',
            label: 'User Category Mapping',
            path: '/masters/user-category-mapping',
            icon: IconLink,
            menuKey: 'masters.user_category_mapping',
          },
          {
            key: 'doc_to_sign_mapping',
            label: 'Document To Sign Mapping',
            path: '/masters/doc-to-sign-mapping',
            icon: IconFileSignature,
            menuKey: 'masters.doc_to_sign_mapping',
          },
          {
            key: 'interviewer_mapping',
            label: 'Department To Interviewer Mapping',
            path: '/masters/interviewer-mapping',
            icon: IconUserCheck,
            menuKey: 'masters.interviewer_mapping',
          },
        ],
      },
      {
        label: 'General Mapping Masters',
        items: [
          {
            key: 'cost_centre_to_company_mapping',
            label: 'Cost Centre To Company Mapping',
            path: '/masters/cost-centre-to-company-mapping',
            icon: IconLink,
            menuKey: 'masters.cost_centre_to_company_mapping',
          },
          {
            key: 'rig_site_mapping',
            label: 'Rig Site Mapping',
            path: '/masters/rig-site-mapping',
            icon: IconLink,
            menuKey: 'masters.rig_site_mapping',
          },
          {
            key: 'company_to_location_mapping',
            label: 'Company To Location Mapping',
            path: '/masters/company-to-location-mapping',
            icon: IconLink,
            menuKey: 'masters.company_to_location_mapping',
          },
        ],
      },
      {
        label: 'HR Mapping Masters',
        items: [
          {
            key: 'fs_catg_to_rig_type_mapping',
            label: 'Category To Rig Type Mapping',
            path: '/masters/fs-catg-to-rig-type-mapping',
            icon: IconLink,
            menuKey: 'masters.fs_catg_to_rig_type_mapping',
          },
          {
            key: 'fs_categories',
            label: 'FS Categories',
            path: '/masters/fs-categories',
            icon: IconTag,
            menuKey: 'masters.fs_categories',
          },
          {
            key: 'rank_classification',
            label: 'Rank Classification',
            path: '/masters/rank-classification',
            icon: IconChevronsUp,
            menuKey: 'masters.rank_classification',
          },
          {
            key: 'nationality_to_emp_type_mapping',
            label: 'Nationality To Emp Type Mapping',
            path: '/masters/nationality-to-emp-type-mapping',
            icon: IconLink,
            menuKey: 'masters.nationality_to_emp_type_mapping',
          },
          {
            key: 'crew_change_reliever_mapping',
            label: 'Crew Change Reliever Mapping',
            path: '/masters/crew-change-reliever-mapping',
            icon: IconLink,
            menuKey: 'masters.crew_change_reliever_mapping',
          },
        ],
      },
      {
        label: 'HSE Mapping Masters',
        items: [
          {
            key: 'wkgrp_indicator_type_mapping',
            label: 'Workgroup To Indicator Type Mapping',
            path: '/masters/wkgrp-indicator-type-mapping',
            icon: IconLink,
            menuKey: 'masters.wkgrp_indicator_type_mapping',
          },
        ],
      },
      {
        label: 'Exception Masters',
        items: [
          {
            key: 'rig_crew_exceptions',
            label: 'Rig Crew Exceptions',
            path: '/masters/rig-crew-exceptions',
            icon: IconAlertTriangle,
            menuKey: 'masters.rig_crew_exceptions',
          },
          {
            key: 'crew_schedule_exceptions',
            label: 'Crew Schedule Exceptions',
            path: '/masters/crew-schedule-exceptions',
            icon: IconAlertTriangle,
            menuKey: 'masters.crew_schedule_exceptions',
          },
        ],
      },
      {
        label: 'Projects',
        items: [
          {
            key: 'project_contract',
            label: 'Project Contract',
            path: '/masters/project-contract',
            icon: IconBriefcase,
            menuKey: 'masters.project_contract',
          },
          {
            key: 'project_drilling_rates',
            label: 'Project Drilling Rates',
            path: '/masters/project-drilling-rates',
            icon: IconTrendingUp,
            menuKey: 'masters.project_drilling_rates',
          },
        ],
      },
      {
        label: 'Drilling',
        items: [
          {
            key: 'drilling_operations',
            label: 'Drilling Operations',
            path: '/masters/drilling-operations',
            icon: IconWrench,
            menuKey: 'masters.drilling_operations',
          },
          {
            key: 'drilling_sections',
            label: 'Drilling Sections',
            path: '/masters/drilling-sections',
            icon: IconLayers,
            menuKey: 'masters.drilling_sections',
          },
          {
            key: 'drilling_work_shift',
            label: 'Drilling Work Shift',
            path: '/masters/drilling-work-shifts',
            icon: IconActivity,
            menuKey: 'masters.drilling_work_shift',
          },
          {
            key: 'drilling_rates',
            label: 'Drilling Rates',
            path: '/masters/drilling-rates',
            icon: IconTrendingUp,
            menuKey: 'masters.drilling_rates',
          },
        ],
      },
      {
        label: 'IT Asset Masters',
        items: [
          {
            key: 'it_asset_types',
            label: 'IT Asset Type',
            path: '/masters/it-asset-types',
            icon: Tag,
            menuKey: 'masters.it_asset_types',
          },
          {
            key: 'it_asset_subtypes',
            label: 'IT Asset Subtype',
            path: '/masters/it-asset-subtypes',
            icon: Tags,
            menuKey: 'masters.it_asset_subtypes',
          },
          {
            key: 'it_asset_mfgs',
            label: 'IT Asset Manufacturer',
            path: '/masters/it-asset-mfgs',
            icon: Factory,
            menuKey: 'masters.it_asset_mfgs',
          },
          {
            key: 'it_asset_models',
            label: 'IT Asset Model',
            path: '/masters/it-asset-models',
            icon: Package,
            menuKey: 'masters.it_asset_models',
          },
          {
            key: 'vendor_types',
            label: 'Vendor Type',
            path: '/masters/vendor-types',
            icon: Tag,
            menuKey: 'masters.vendor_types',
          },
          {
            key: 'vendors',
            label: 'Vendor',
            path: '/masters/vendors',
            icon: Truck,
            menuKey: 'masters.vendors',
          },
        ],
      },
    ],
  },
  {
    key: 'it_asset',
    label: 'IT Asset',
    icon: Laptop,
    sections: [
      {
        items: [
          {
            key: 'it_assets',
            label: 'IT Assets',
            path: '/it-asset/it-assets',
            icon: Laptop,
            menuKey: 'it_asset.it_assets',
          },
          {
            key: 'it_asset_holders',
            label: 'IT Asset Holders',
            path: '/it-asset/it-asset-holders',
            icon: IconUserCheck,
            menuKey: 'it_asset.it_asset_holders',
          },
          {
            key: 'it_accessories',
            label: 'IT Accessories',
            path: '/it-asset/it-accessories',
            icon: Cable,
            menuKey: 'masters.it_accessories',
          },
          {
            key: 'it_accessory_holders',
            label: 'IT Accessory Holders',
            path: '/it-asset/it-accessory-holders',
            icon: Cable,
            menuKey: 'it_asset.it_accessory_holders',
          },
          {
            key: 'it_asset_report',
            label: 'Asset Report',
            path: '/it-asset/report',
            icon: IconClipboard,
            menuKey: 'reports.it_assets',
          },
        ],
      },
    ],
  },
  {
    key: 'drilling',
    label: 'Drilling Details',
    icon: Drill,
    sections: [
      {
        items: [
          {
            key: 'drilling_information',
            label: 'Drilling Information',
            path: '/drilling/drilling-information',
            icon: Drill,
            menuKey: 'drilling.drilling_information',
          },
          {
            key: 'drilling_report',
            label: 'Drilling Report',
            path: '/drilling/drilling-report',
            icon: IconClipboard,
            menuKey: 'drilling.drilling_report',
          },
          {
            key: 'performance_dashboard',
            label: 'Performance Dashboard',
            path: '/drilling/performance-dashboard',
            icon: IconTrendingUp,
            menuKey: 'drilling.performance_dashboard',
          },
          {
            key: 'operations_analytics',
            label: 'Operations Analytics',
            path: '/drilling/operations-analytics',
            icon: IconActivity,
            menuKey: 'drilling.operations_analytics',
          },
          {
            key: 'drilling_tripping_analysis',
            label: 'Drilling & Tripping Analysis',
            path: '/drilling/drilling-tripping-analysis',
            icon: IconTrendingUp,
            menuKey: 'drilling.drilling_tripping_analysis',
          },
          {
            key: 'drilling_daily_data',
            label: 'Drilling Daily Data',
            path: '/drilling/drilling-daily-data',
            icon: IconClipboard,
            menuKey: 'drilling.drilling_daily_data',
          },
        ],
      },
    ],
  },
  {
    key: 'qhse',
    label: 'QHSE',
    icon: IconShieldCheck,
    sections: [
      {
        items: [
          {
            key: 'rig_certificates',
            label: 'Rig Certificates',
            path: '/qhse/rig-certificates',
            icon: IconFileSignature,
            menuKey: 'qhse.rig_certificates',
          },
          {
            key: 'rig_certificate_schedule',
            label: 'Rig Certificate Schedule',
            path: '/qhse/rig-certificate-schedule',
            icon: IconClipboard,
            menuKey: 'qhse.rig_certificate_schedule',
          },
          {
            key: 'activity_monitor',
            label: 'Activity Monitor',
            path: '/qhse/activity-monitor',
            icon: IconActivity,
            menuKey: 'qhse.activity_monitor',
          },
          {
            key: 'activity_closure_analysis',
            label: 'Activity Closure Analysis',
            path: '/qhse/activity-closure-analysis',
            icon: IconTrendingUp,
            menuKey: 'qhse.activity_closure_analysis',
          },
          {
            key: 'incident_details',
            label: 'Incident Details',
            path: '/qhse/incident-details',
            icon: IconAlertTriangle,
            menuKey: 'qhse.incident_details',
          },
          {
            key: 'incident_root_cause',
            label: 'Incident Root Cause',
            path: '/qhse/incident-root-cause',
            icon: IconGitBranch,
            menuKey: 'qhse.incident_root_cause',
          },
          {
            key: 'incident_actions',
            label: 'Incident Actions',
            path: '/qhse/incident-actions',
            icon: ClipboardList,
            menuKey: 'qhse.incident_actions',
          },
          {
            key: 'incident_register',
            label: 'Incident Register',
            path: '/qhse/incident-register',
            icon: IconClipboard,
            menuKey: 'qhse.incident_register',
          },
          {
            key: 'hazard_id_card',
            label: 'Hazard ID Card',
            path: '/qhse/hazard-id-card',
            icon: IconShieldCheck,
            menuKey: 'qhse.hazard_id_card',
          },
          {
            key: 'mis_hse_return',
            label: 'MIS Monthly HSE Return',
            path: '/qhse/mis-hse-return',
            icon: IconClipboard,
            menuKey: 'qhse.mis_hse_return',
          },
          {
            key: 'mis_hse_review',
            label: 'Monthly HSE Review',
            path: '/qhse/mis-hse-review',
            icon: IconTrendingUp,
            menuKey: 'qhse.mis_hse_review',
          },
          {
            key: 'hse_drill_record',
            label: 'HSE Drills / Exercises',
            path: '/qhse/hse-drill-record',
            icon: IconAlertTriangle,
            menuKey: 'qhse.hse_drill_record',
          },
          {
            key: 'hse_weekly_drill',
            label: 'HSE Weekly Drill',
            path: '/qhse/hse-weekly-drill',
            icon: IconClipboard,
            menuKey: 'qhse.hse_weekly_drill',
          },
          {
            key: 'hse_drill_report',
            label: 'HSE Drill Report',
            path: '/qhse/hse-drill-report',
            icon: IconTrendingUp,
            menuKey: 'qhse.hse_drill_report',
          },
          {
            key: 'leading_indicators',
            label: 'HSE - Leading Indicators',
            path: '/qhse/leading-indicators',
            icon: IconTrendingUp,
            menuKey: 'qhse.leading_indicators',
          },
          {
            key: 'lagging_indicators',
            label: 'HSE - Lagging Indicators',
            path: '/qhse/lagging-indicators',
            icon: IconTrendingUp,
            menuKey: 'qhse.lagging_indicators',
          },
        ],
      },
    ],
  },
  {
    key: 'reports',
    label: 'Reports',
    icon: IconClipboard,
    sections: [
      {
        items: [
          {
            key: 'incidents',
            label: 'Incidents',
            path: '/reports/incidents',
            icon: IconAlertTriangle,
            menuKey: 'reports.incidents',
          },
          {
            key: 'hazard_cards',
            label: 'Hazard Cards',
            path: '/reports/hazard-cards',
            icon: IconShieldCheck,
            menuKey: 'reports.hazard_cards',
          },
        ],
      },
    ],
  },
  {
    key: 'admin',
    label: 'Admin',
    icon: IconShield,
    adminOnly: true,
    sections: [
      {
        items: [
          { key: 'user_rights', label: 'User Rights', path: '/admin/user-rights', icon: IconShield },
          {
            key: 'user_management', label: 'User Management', path: '/admin/user-management', icon: IconUsers, 
            menuKey: 'admin.user_management'},
          { key: 'audit_trail', label: 'Audit Trail', path: '/admin/audit-trail', icon: IconHistory },
          { key: 'email_log', label: 'Email Log', path: '/admin/email-log', icon: IconMail },
          {
            key: 'approval_codes',
            label: 'Approval Code',
            path: '/masters/approval-codes',
            icon: IconFileSignature,
            menuKey: 'masters.approval_codes',
          },
          {
            key: 'approver_mapping',
            label: 'Approver Mapping',
            path: '/admin/approver-mapping',
            icon: IconUserCheck,
            menuKey: 'admin.approver_mapping',
          },
        ],
      },
    ],
  },
]

// Every leaf page that resolves to a real route, for Topbar breadcrumb
// lookups — parents themselves aren't routes, only their sections' items are.
export const navSections = navTree.flatMap((item) =>
  item.sections ? item.sections.flatMap((s) => s.items) : [item]
)
